package lgjx

type ApiGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	OrderApi
	ApplyApi
	PayApi
	LetterApi
	RevokeApi
	DelayApi
	RefundApi
	ClaimApi
	LogoutApi
	InvoiceApi
	InvoiceApplyApi
	ProjectApi
	SettingApi
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}

type TestApiGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	TestOrderApi
	TestApplyApi
	TestPayApi
	TestLetterApi
	TestRevokeApi
	TestDelayApi
	TestRefundApi
	TestClaimApi
	TestLogoutApi
	TestInvoiceApi
	TestInvoiceApplyApi
	TestProjectApi
	TestSettingApi
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
