package lgjx

type RouterGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	OrderRouter
	ApplyRouter
	PayRouter
	LetterRouter
	RevokeRouter
	DelayRouter
	RefundRouter
	ClaimRouter
	LogoutRouter
	InvoiceRouter
	InvoiceApplyRouter
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}

type TestRouterGroup struct {
	TestOrderRouter
	TestApplyRouter
	TestPayRouter
	TestLetterRouter
	TestRevokeRouter
	TestDelayRouter
	TestRefundRouter
	TestClaimRouter
	TestLogoutRouter
	TestInvoiceRouter
	TestInvoiceApplyRouter
}
