package lgjx

type RouterGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	JRAPIRouter
	OrderRouter
	ApplyRouter
	PayRouter
	LetterRouter
	RevokeRouter
	DelayRouter
	RefundRouter
	ClaimRouter
	LogoutRouter
	InvoiceRouter
	InvoiceApplyRouter
	ProjectRouter
	TemplateRouter
	FileRouter
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}

type TestRouterGroup struct {
	TESTJRAPIRouter
	TestOrderRouter
	TestApplyRouter
	TestPayRouter
	TestLetterRouter
	TestRevokeRouter
	TestDelayRouter
	TestRefundRouter
	TestClaimRouter
	TestLogoutRouter
	TestInvoiceRouter
	TestInvoiceApplyRouter
	TestProjectRouter
	TestTemplateRouter
	TestFileRouter
}
