package lgjx

type ServiceGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	OrderService
	ApplyService
	PayService
	LetterService
	RevokeService
	DelayService
	RefundService
	ClaimService
	LogoutService
	InvoiceService
	InvoiceApplyService
	ProjectService
	TemplateService
	FileService
	SettingService
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}

type TestServiceGroup struct {
	TestOrderService
	TestApplyService
	TestPayService
	TestLetterService
	TestRevokeService
	TestDelayService
	TestRefundService
	TestClaimService
	TestLogoutService
	TestInvoiceService
	TestInvoiceApplyService
	TestProjectService
	TestTemplateService
	TestFileService
	TestSettingService
}
